#!/bin/sh
# For those without git, this script will download ec0.

wget --no-check-certificate https://github.com/KenKundert/ec0/tarball/master
tar zxf master
rm -rf master ec0
mv KenKundert-ec0-* ec0
